eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10010/eureka

server:
  port: 8001
spring:
  application:
    name: user
