eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka

#management.endpoints.web.exposure.include: hystrix.stream

#zuul:
#  ignoredServices: '*'
#  routes:
#    micro-user: /muser/**
#zuul:
#  routes:
#    users:
#      path: /muser/**
#      serviceId: micro-user

---
server:
  port: 9001
spring:
#  profiles: movie1
  application:
    name: micro-movie

