server:
  port: 10020
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10010/eureka
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/,classpath:/config/gateway
  application:
    name: configserver
  profiles:
    active: native

management:
  endpoints:
    web:
      exposure:
        include: "*"
