server:
  port: 9006
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config
#          addLabelLocations: false
  application:
    name: configserver
  profiles:
    active: native

management:
  endpoints:
    web:
      exposure:
        include: "*"

