eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

#zuul:
#  ignoredServices: '*'
#  routes:
#    micro-user: /user/**
zuul:
#  ignoredPatterns: /**/admin/**
  routes:
    users:
      path: /myusers/**
      serviceId: micro-user-v1
#      stripPrefix: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
server:
  port: 9005
spring:
  application:
    name: gateway