
---
server:
  port: 8761
spring:
  profiles: eureka1
  application:
    name: eureka1
eureka:
  instance:
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: https://eureka2/eureka/

---
server:
  port: 8762
spring:
  profiles: eureka2
  application:
    name: eureka2
eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: https://eureka1/eureka/

