
server:
  port: 8000
eureka:
  instance:
#    preferIpAddress: true
    hostname: eureka1
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://localhost:${server.port}/eureka/
spring:
  application:
    name: eureka1
#    name: eureka-standalone
#---
#server:
#  port: 8000
#spring:
#  profiles: eureka1
#  application:
#    name: eureka1
#eureka:
#  instance:
#    hostname: eureka1
#  client:
#    serviceUrl:
#      defaultZone: https://eureka2/eureka/
#
#---
#server:
#  port: 8762
#spring:
#  profiles: eureka2
#  application:
#    name: eureka2
#eureka:
#  instance:
#    hostname: eureka2
#  client:
#    serviceUrl:
#      defaultZone: https://eureka1/eureka/

