eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

---
server:
  port: 8001
spring:
  profiles: user1
  application:
    name: micro-user

---
server:
  port: 8002
spring:
  profiles: user2
  application:
    name: micro-user
